# Generated by Django 4.1.7 on 2023-03-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.PositiveSmallIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
