# Generated by Django 4.1.7 on 2023-03-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0003_film_description_film_imdb_rating_film_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='film',
            name='type',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
