# Generated by Django 4.1.7 on 2023-03-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0004_film_director_film_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters'),
        ),
        migrations.AlterField(
            model_name='film',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
