# Generated by Django 4.1.7 on 2023-04-07 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0006_additionalinfo_film_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='movie_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Sci-fi'), (0, 'Unknown'), (5, 'Action'), (1, 'Horror'), (2, 'Comedy'), (4, 'Fantasy')], default=0),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, default='')),
                ('grade', models.PositiveSmallIntegerField(default=5)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmyweb.film')),
            ],
        ),
    ]
