# Generated by Django 4.1.7 on 2023-04-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0007_alter_additionalinfo_movie_type_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='movie_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (4, 'Fantasy'), (2, 'Comedy'), (0, 'Unknown'), (3, 'Sci-fi'), (5, 'Action')], default=0),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('titles', models.ManyToManyField(to='filmyweb.film')),
            ],
        ),
    ]
