# Generated by Django 4.1.7 on 2023-04-08 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filmyweb', '0008_alter_additionalinfo_movie_type_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='titles',
            field=models.ManyToManyField(related_name='Actors', to='filmyweb.film'),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='movie_type',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Fantasy'), (0, 'Unknown'), (2, 'Comedy'), (5, 'Action'), (1, 'Horror'), (3, 'Sci-fi')], default=0),
        ),
    ]
