# Generated by Django 4.1.7 on 2023-04-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0010_alter_additionalinfo_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='movie_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Horror'), (5, 'Action'), (3, 'Sci-fi'), (0, 'Unknown'), (2, 'Comedy'), (4, 'Fantasy')], default=0),
        ),
    ]
